# Generated by Django 5.0.3 on 2024-03-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsInternalExternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RealisationsProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=75)),
                ('arrangement', models.CharField(max_length=75)),
                ('slug', models.SlugField(max_length=75, unique=True)),
                ('design_office', models.CharField(blank=True, max_length=75)),
                ('photo', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(null=True, upload_to='realisations_images')),
            ],
        ),
        migrations.CreateModel(
            name='RealisationsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsSubgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('main_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candelight_website.productsinternalexternal')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('main_image', models.ImageField(null=True, upload_to='products_images')),
                ('main_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candelight_website.productsinternalexternal')),
                ('sub_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candelight_website.productssubgroup')),
            ],
        ),
        migrations.CreateModel(
            name='RealisationsPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='realisations_additional_images')),
                ('main_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candelight_website.realisationsproject')),
            ],
        ),
        migrations.AddField(
            model_name='realisationsproject',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candelight_website.realisationstype'),
        ),
    ]
