# Generated by Django 5.0 on 2023-12-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candelight_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisationsproject',
            name='image',
            field=models.ImageField(null=True, upload_to='realisations_images'),
        ),
    ]
