# Generated by Django 5.0 on 2023-12-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candelight_website', '0002_realisationsproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisationsproject',
            name='description',
            field=models.TextField(max_length=450),
        ),
    ]
