# Generated by Django 5.0 on 2023-12-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candelight_website', '0003_alter_realisationsproject_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsInternalExternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_image', models.ImageField(null=True, upload_to='products_images')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candelight_website.productsinternalexternal')),
            ],
        ),
    ]
