# Generated by Django 5.0 on 2023-12-26 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candelight_website', '0004_productsinternalexternal_productsproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsSubgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='productsproduct',
            old_name='group',
            new_name='main_group',
        ),
        migrations.AddField(
            model_name='productsproduct',
            name='sub_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candelight_website.productssubgroup'),
        ),
    ]
