# Generated by Django 5.0 on 2024-01-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candelight_website', '0006_productsproduct_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productssubgroup',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
