# Generated by Django 5.0 on 2024-01-06 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candelight_website', '0007_productssubgroup_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productssubgroup',
            name='main_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candelight_website.productsinternalexternal'),
            preserve_default=False,
        ),
    ]
