# Generated by Django 5.0 on 2024-01-06 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candelight_website', '0008_productssubgroup_main_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productssubgroup',
            name='main_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candelight_website.productsinternalexternal'),
        ),
    ]
