# Generated by Django 5.0 on 2024-01-07 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candelight_website', '0010_rename_title_realisationsproject_arrangement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealisationsPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='realisations_additional_images')),
                ('main_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candelight_website.realisationsproject')),
            ],
        ),
    ]
