# Generated by Django 5.0 on 2024-01-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candelight_website', '0011_realisationsphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisationsproject',
            name='slug',
            field=models.SlugField(default=1, max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realisationsproject',
            name='design_office',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='realisationsproject',
            name='photo',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
