# Generated by Django 5.0 on 2024-01-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candelight_website', '0012_realisationsproject_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisationsproject',
            name='slug',
            field=models.SlugField(max_length=75, unique=True),
        ),
    ]
