# Generated by Django 5.0 on 2024-01-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candelight_website', '0013_alter_realisationsproject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisationsproject',
            name='design_office',
            field=models.CharField(blank=True, default=1, max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realisationsproject',
            name='photo',
            field=models.CharField(blank=True, default=1, max_length=120),
            preserve_default=False,
        ),
    ]
